vim.api.nvim_create_user_command("Kolory", "FzfLua colorschemes", {})
vim.api.nvim_create_user_command("CDFD", "lua CDFD()", {})
vim.api.nvim_create_user_command("CD", "lua CD()", {})
vim.api.nvim_create_user_command("CDE", "lua CDE()", {})
vim.api.nvim_create_user_command("CDG", "lua CDG()", {})
vim.api.nvim_create_user_command("NvimAppName", "lua print(NvimAppName())", {})
vim.api.nvim_create_user_command("Config", "lua NvimConfig()", {})
