vim.keymap.set("n", [[<s-enter>]], "mzO<esc>`z", { desc = "Dodaje pustą linię powyżej bieżącej" })
vim.keymap.set("n", [[<enter>]], "mzo<esc>`z", { desc = "Dodaje pustą linię poniżej bieżącej" })
vim.keymap.set("n", [[<leader>n]], "<cmd>lua CDFD()<cr><cmd>Neotree toggle<cr>", { desc = "Uruchamia menadżer plików NeoTree" })
vim.keymap.set("n", [[\]], "<cmd>Neotree toggle<cr>", { desc = "Uruchamia menadżer plików NeoTree" })
vim.keymap.set({"n", "x"}, [[gh]], "^", { desc = "Początek linii" })
vim.keymap.set({"n", "x"}, [[gl]], "$", { desc = "Koniec linii" })
vim.keymap.set("n", [[<leader>,]], [[<cmd>bp<cr>]], { desc = "Poprzeni bufor" })
vim.keymap.set("n", [[<leader>.]], [[<cmd>bn<cr>]], { desc = "Następny bufor" })
vim.keymap.set("n", [[<leader>w]], [[<cmd>w<cr>]], { desc = "Zapisanie zmian" })
vim.keymap.set("n", [[qq]], [[<cmd>q<cr>]], { desc = "Wyjśćie" })
vim.keymap.set("n", [[<leader>;]], [[:]], { desc = "Wejście do trybu COMMAND" })
vim.keymap.set("n", [[M]], [[`m]], { desc = "Przechodzi do znacznika `m`" })
vim.keymap.set("n", [[<c-h>]], [[<c-w><c-h>]], { desc = "Przechodzi do okna po lewej" })
vim.keymap.set("n", [[<c-l>]], [[<c-w><c-l>]], { desc = "Przechodzi do okna po prawej" })
vim.keymap.set("n", [[<c-j>]], [[<c-w><c-j>]], { desc = "Przechodzi do okna niżej" })
vim.keymap.set("n", [[<c-k>]], [[<c-w><c-k>]], { desc = "Przechodzi do okna wyżej" })
vim.keymap.set("n", [[<leader>so]], [[<cmd>luafile %<cr>]], { desc = "Wczytuje bieżący plik Lua" })
vim.keymap.set("n", [[<leader>d]], [[<cmd>bd<cr>]], { desc = "Usuwa bufor" })
vim.keymap.set("n", [[gf]], [[<cmd>edit <cfile><cr>]], { desc = "Otwiera plik pod kursorem" })
vim.keymap.set("n", [[dh]], "xd0", { desc = "Usuwa od kursora do początku linii" })
vim.keymap.set("n", [[dl]], "d$", { desc = "Usuwa od kursora do końca linii" })
vim.keymap.set("n", "<leader>sv", "<cmd>vs<cr>", { desc = "Dzieli okno w pionie" })
vim.keymap.set("n", "<leader>sp", "<cmd>sp<cr>", { desc = "Dzieli okno w poziomie" })
vim.keymap.set("n", "<leader>v", "<cmd>lua NvimConfig()<cr>", { desc = "Wyszukiwarka plików konfiguracyjnych" })
vim.keymap.set("n", "yA", "<cmd>%yank<cr>", { desc = "Kopiuje całą zawartość pliku do rejestru" })
vim.keymap.set("n", "<space>m", "<cmd>lua CopyReg()<cr>", { desc = "Kopiuje zawartość głównego rejestru do rejestru 'x'" })
vim.keymap.set("n", "M", '"xp', { desc = "Wkleja zawartość rejestru 'x', standardowo klawisz 'M' przenosi kursor na środek ekranu" })
vim.keymap.set("n", "<leader>C", "<cmd>enew<cr>", { desc = "Tworzy nowy plik" })
vim.keymap.set("n", "<F9>", "<cmd>lua KolorPora()<cr>", { desc = "Zmiana tematu kolorystycznego w zależności od pory dnia" })
vim.keymap.set("n", "<c-_>", "<Plug>kommentary_line_default", { desc = "<Ctrl + /> Tworzy komentarz" })
vim.keymap.set("x", "<c-_>", "<Plug>kommentary_visual_default", { desc = "<Ctrl + /> Tworzy komentarz" })
vim.keymap.set("n", "<leader>u", "<cmd>UndotreeToggle<cr>", { desc = "Rejestr zmian Undotree" })
vim.keymap.set("n", "+", "<C-a>", { desc = "Zwiększa wartość liczby" })
vim.keymap.set("n", "-", "<C-x>", { desc = "Zmniejsza wartość liczby" })
vim.keymap.set("n", "<leader>b", "<cmd>FzfLua buffers<cr>", { desc = "Przełączanie pomiędzy buforami" })
vim.keymap.set("n", "<tab>", "<cmd>e #<cr>", { desc= "Przełączanie pomiędzy dwoma ostatnimi buforami" })
vim.keymap.set("n", "<leader>o", "<cmd>only<cr>", { desc = "Pozostawia otwarte tylko aktywne okno" })
vim.keymap.set("n", "<leader>c", "<cmd>close<cr>", { desc = "Zamyka aktywne okno" })
vim.keymap.set("n", "<esc>", "<cmd>nohl<cr>", { silent = true, desc = "Wyłącza wyróżnianie szukanego tekstu" })
-- Mapowanie znaczników (undo) w trybie INSERT, po wprowadzeniu jednego ze znaków , . ! ? ; :
local undo_ch = { ",", ".", "!", "?", ";", ":" }
for _, ch in ipairs(undo_ch) do
    vim.keymap.set("i", ch, ch .. "<c-g>u")
end
